# Generated by Django 5.0.1 on 2024-01-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_request_points_user_requests_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='worst_case_points',
            field=models.IntegerField(default=0),
        ),
    ]
