# Generated by Django 5.0.1 on 2024-01-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_worst_case_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='request_points',
        ),
        migrations.AddField(
            model_name='outgoingrequest',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='outgoingrequest',
            name='game_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
