# Generated by Django 4.2.4 on 2024-01-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_outgoingrequest_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingrequest',
            name='num1',
        ),
        migrations.RemoveField(
            model_name='incomingrequest',
            name='num2',
        ),
        migrations.RemoveField(
            model_name='incomingrequest',
            name='num3',
        ),
        migrations.AddField(
            model_name='incomingrequest',
            name='play1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomingrequest',
            name='play2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomingrequest',
            name='play3',
            field=models.BooleanField(default=False),
        ),
    ]
