# Generated by Django 4.2.4 on 2024-01-27 11:45

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_incomingrequest_num1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingrequest',
            name='valid_until',
            field=models.DateTimeField(default=base.models.default_valid_until),
        ),
        migrations.AddField(
            model_name='outgoingrequest',
            name='valid_until',
            field=models.DateTimeField(default=base.models.default_valid_until),
        ),
    ]
