# Generated by Django 4.2.4 on 2024-01-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_outgoingrequest_request_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='', max_length=255)),
                ('receiver_name', models.CharField(default='', max_length=255)),
                ('game_link', models.CharField(default='', max_length=255)),
                ('game_forfeited', models.BooleanField(default=False)),
                ('sender_wins', models.IntegerField(default=0)),
                ('receiver_wins', models.IntegerField(default=0)),
                ('num1', models.IntegerField(default=0)),
                ('num2', models.IntegerField(default=0)),
                ('num3', models.IntegerField(default=0)),
                ('play1', models.BooleanField(default=False)),
                ('play2', models.BooleanField(default=False)),
                ('play3', models.BooleanField(default=False)),
            ],
        ),
    ]
