services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    ports:
      - "6000:3306"

  djangoapp:
    container_name: djangoapp
    image: sarvesh717/infin8:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    env_file:
      - .env
