# Generated by Django 5.0.1 on 2024-01-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_outgoingrequest_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingrequest',
            name='turn',
            field=models.IntegerField(default=1),
        ),
    ]
