# Generated by Django 4.2.4 on 2024-01-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
