# Generated by Django 4.2.4 on 2024-02-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_status_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='num1',
        ),
        migrations.RemoveField(
            model_name='status',
            name='num2',
        ),
        migrations.RemoveField(
            model_name='status',
            name='num3',
        ),
        migrations.RemoveField(
            model_name='status',
            name='play1',
        ),
        migrations.RemoveField(
            model_name='status',
            name='play2',
        ),
        migrations.RemoveField(
            model_name='status',
            name='play3',
        ),
    ]
